org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.9
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.21.9-1.21.11_1.0.0-fabric
group=net.creeperucan.locatix

# Dependencies
fabric_api_version=0.134.1+1.21.9
