org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.9
parchment_mappings_version=2025.10.05
minecraft_version=1.21.9
minecraft_version_range=[1.21.9, 1.21.11]
neo_version=21.9.16-beta

## Mod Properties
mod_id=locatix
mod_name=Locatix
mod_license=MIT
mod_version=1.21.9-1.21.11_1.0.0-neoforge
mod_group_id=net.creeperucan.locatix
